"""
thesis_plots.py - Thesis-quality figures from experiment CSVs
=============================================================

Reads CSVs generated by experiments.py and produces publication-ready plots.

MANDATORY PLOTS (per thesis requirement):
  Fig 1  Runtime by benchmark        (scalability)
  Fig 2  Baseline vs Advanced        (grouped bar comparison)
  Fig 3  Match distribution          (matched / unmatched stacked bar)

SUPPLEMENTARY PLOTS:
  Fig 4  Benchmark overview          (AND gates + depth)
  Fig 5  WL convergence              (labels vs k)
"""

import os, sys, csv
import numpy as np

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

CSV_DIR   = os.path.join(PROJECT_ROOT, "results", "csv")
PLOTS_DIR = os.path.join(PROJECT_ROOT, "results", "plots")
os.makedirs(PLOTS_DIR, exist_ok=True)

# --- colour palette ------------------------------------------------
C = {
    'baseline':  '#2196F3',   # blue
    'advanced':  '#4CAF50',   # green
    'matched':   '#4CAF50',
    'unmatched': '#F44336',   # red
    'fp':        '#FF9800',   # orange
    'accent':    '#9C27B0',   # purple
    'dark':      '#1565C0',
    'teal':      '#009688',
    'grey':      '#9E9E9E',
}


def _read(fn):
    path = os.path.join(CSV_DIR, fn)
    if not os.path.exists(path):
        print(f"  [!] Missing CSV: {fn}")
        return []
    with open(path, 'r', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def _save(fig, name):
    path = os.path.join(PLOTS_DIR, name)
    fig.savefig(path, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    print(f"  [PLOT] {name}")


# ================================================================
#  FIG 1 — RUNTIME BY BENCHMARK (scalability)
# ================================================================
def plot_scalability():
    rows = _read('table5_scalability.csv')
    if not rows:
        return

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))

    bits  = [int(r['Bits']) for r in rows]
    nodes = [int(r['Nodes']) for r in rows]
    wl_ms = [float(r['WL ms']) for r in rows]
    tot   = [float(r['Total ms']) for r in rows]

    # Left: nodes vs bits
    ax1.bar(range(len(bits)), nodes, color=C['baseline'], alpha=.85)
    ax1.set_xticks(range(len(bits)))
    ax1.set_xticklabels([f"{b}-bit" for b in bits])
    ax1.set_ylabel('AIG Nodes')
    ax1.set_title('AIG Size vs Adder Width', fontweight='bold')
    for i, v in enumerate(nodes):
        ax1.text(i, v + 5, str(v), ha='center', fontsize=9)

    # Right: runtime vs bits
    ax2.plot(bits, tot, 'o-', color=C['dark'], lw=2.5, ms=9, label='Total')
    ax2.plot(bits, wl_ms, 's--', color=C['advanced'], lw=2, ms=7, label='WL Hash')
    ax2.fill_between(bits, tot, alpha=.10, color=C['baseline'])
    ax2.set_xlabel('Adder Bit-Width')
    ax2.set_ylabel('Time (ms)')
    ax2.set_title('Pipeline Runtime vs Design Size', fontweight='bold')
    ax2.set_xticks(bits)
    ax2.legend()

    fig.suptitle('Fig 1: Scalability Analysis', fontsize=13, fontweight='bold', y=1.02)
    _save(fig, 'thesis_fig1_scalability.png')


# ================================================================
#  FIG 2 — BASELINE vs ADVANCED (grouped bar)
# ================================================================
def plot_comparison():
    rows = _read('table4_comparison.csv')
    if not rows:
        return

    fig, ax = plt.subplots(figsize=(13, 6))

    pairs    = [r['Pair'] for r in rows]
    bl_pct   = [float(r['Baseline %']) for r in rows]
    adv_pct  = [float(r['Advanced %']) for r in rows]
    fp_count = [int(r['False Pos']) for r in rows]

    x = np.arange(len(pairs))
    w = 0.32

    bars_bl  = ax.bar(x - w/2, bl_pct,  w, label='Baseline (Fingerprint)',
                      color=C['baseline'], alpha=.85)
    bars_adv = ax.bar(x + w/2, adv_pct, w, label='Advanced (WL Hash)',
                      color=C['advanced'], alpha=.85)

    # Annotate values
    for i in range(len(pairs)):
        ax.text(x[i] - w/2, bl_pct[i]  + 1.5, f"{bl_pct[i]:.0f}%",
                ha='center', fontsize=9, fontweight='bold')
        ax.text(x[i] + w/2, adv_pct[i] + 1.5, f"{adv_pct[i]:.0f}%",
                ha='center', fontsize=9, fontweight='bold')
        if fp_count[i]:
            mid = (bl_pct[i] + adv_pct[i]) / 2
            ax.annotate(f'{fp_count[i]} FP', xy=(x[i], mid),
                        fontsize=8, color=C['fp'], fontweight='bold',
                        ha='center')

    # Short labels
    short = [p.replace(' vs ', '\nvs\n') for p in pairs]
    ax.set_xticks(x)
    ax.set_xticklabels(short, fontsize=8)
    ax.set_ylabel('Cone Match Rate (%)')
    ax.set_ylim(0, 115)
    ax.legend(fontsize=10, loc='upper right')
    ax.set_title('Fig 2: Baseline vs Advanced Cone Matching',
                 fontweight='bold', fontsize=13)
    ax.axhline(y=100, color=C['grey'], ls=':', lw=0.8)
    _save(fig, 'thesis_fig2_comparison.png')


# ================================================================
#  FIG 3 — MATCH DISTRIBUTION (stacked bar: matched / unmatched)
# ================================================================
def plot_match_distribution():
    bl_rows  = _read('table2_baseline.csv')
    adv_rows = _read('table3_advanced.csv')
    if not bl_rows or not adv_rows:
        return

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6), sharey=True)

    def _draw(ax, rows, title):
        pairs = [r['Pair'].replace(' vs ', '\nvs\n') for r in rows]
        matched   = [int(r['Matched'])   for r in rows]
        unmatched = [int(r['Unmatched']) for r in rows]
        x = np.arange(len(pairs))
        ax.bar(x, matched,   .55, label='Matched',   color=C['matched'],   alpha=.85)
        ax.bar(x, unmatched, .55, bottom=matched, label='Unmatched', color=C['unmatched'], alpha=.85)
        for i in range(len(pairs)):
            total = matched[i] + unmatched[i]
            if matched[i]:
                ax.text(i, matched[i]/2, str(matched[i]),
                        ha='center', va='center', fontweight='bold', fontsize=10, color='white')
            if unmatched[i]:
                ax.text(i, matched[i] + unmatched[i]/2, str(unmatched[i]),
                        ha='center', va='center', fontweight='bold', fontsize=10, color='white')
        ax.set_xticks(x)
        ax.set_xticklabels(pairs, fontsize=7)
        ax.set_ylabel('Number of Cones')
        ax.set_title(title, fontweight='bold')
        ax.legend(fontsize=9)

    _draw(ax1, bl_rows,  'Baseline (Structural Fingerprint)')
    _draw(ax2, adv_rows, 'Advanced (WL Hash, k=3)')

    fig.suptitle('Fig 3: Matched vs Unmatched Cones per Experiment Pair',
                 fontsize=13, fontweight='bold', y=1.02)
    _save(fig, 'thesis_fig3_distribution.png')


# ================================================================
#  FIG 4 — BENCHMARK OVERVIEW (supplementary)
# ================================================================
def plot_benchmark_overview():
    rows = _read('table1_benchmark.csv')
    if not rows:
        return

    # Exclude optimisation variants for cleaner chart
    rows = [r for r in rows if '_O0' not in r['Design']
            and '_O1' not in r['Design'] and '_O2' not in r['Design']]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    names = [r['Design'] for r in rows]
    ands  = [int(r['AND']) for r in rows]
    deps  = [int(r['Depth']) for r in rows]
    y     = range(len(names))

    ax1.barh(list(y), ands, color=C['baseline'], alpha=.85)
    ax1.set_yticks(list(y)); ax1.set_yticklabels(names, fontsize=9)
    ax1.set_xlabel('AND Gate Count')
    ax1.set_title('AIG Complexity', fontweight='bold')
    for i, v in enumerate(ands):
        ax1.text(v + 1, i, str(v), va='center', fontsize=9)

    ax2.barh(list(y), deps, color=C['teal'], alpha=.85)
    ax2.set_yticks(list(y)); ax2.set_yticklabels(names, fontsize=9)
    ax2.set_xlabel('Graph Depth')
    ax2.set_title('AIG Depth', fontweight='bold')
    for i, v in enumerate(deps):
        ax2.text(v + 0.3, i, str(v), va='center', fontsize=9)

    fig.suptitle('Fig 4: Benchmark Circuit Overview', fontsize=13,
                 fontweight='bold', y=1.02)
    _save(fig, 'thesis_fig4_benchmark.png')


# ================================================================
#  FIG 5 — WL CONVERGENCE (supplementary)
# ================================================================
def plot_convergence():
    rows = _read('exp_convergence.csv')
    if not rows:
        return

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    ks   = [int(r['k']) for r in rows]
    uh   = [int(r['Unique Hashes']) for r in rows]
    avgL = [float(r['Avg Labels']) for r in rows]

    ax1.plot(ks, uh, 'o-', color=C['baseline'], lw=2.5, ms=9)
    ax1.set_xlabel('WL Iterations (k)')
    ax1.set_ylabel('Unique Cone Hashes')
    ax1.set_title('Cone Discrimination vs k', fontweight='bold')
    ax1.set_xticks(ks); ax1.set_ylim(bottom=0)

    ax2.plot(ks, avgL, 's-', color=C['unmatched'], lw=2.5, ms=9)
    ax2.fill_between(ks, avgL, alpha=.12, color=C['unmatched'])
    ax2.set_xlabel('WL Iterations (k)')
    ax2.set_ylabel('Avg Unique Labels per Cone')
    ax2.set_title('Label Refinement vs k', fontweight='bold')
    ax2.set_xticks(ks)

    fig.suptitle('Fig 5: WL Convergence Study (adder_8bit)',
                 fontsize=13, fontweight='bold', y=1.02)
    _save(fig, 'thesis_fig5_convergence.png')


# ================================================================
#  FIG 6 — FALSE POSITIVE HIGHLIGHT (case study helper)
# ================================================================
def plot_case_study():
    rows = _read('table6_case_study.csv')
    if not rows:
        return

    fig, ax = plt.subplots(figsize=(10, 5))

    cones = [r['Cone'] for r in rows]
    fp_match = [r['FP Match'] == 'True' for r in rows]
    wl_match = [r['WL Match'] == 'True' for r in rows]

    x = np.arange(len(cones))
    w = 0.35

    colors_fp = [C['matched'] if m else C['unmatched'] for m in fp_match]
    colors_wl = [C['matched'] if m else C['unmatched'] for m in wl_match]

    ax.bar(x - w/2, [1]*len(cones), w, color=colors_fp, alpha=.85,
           edgecolor='black', linewidth=.5)
    ax.bar(x + w/2, [1]*len(cones), w, color=colors_wl, alpha=.85,
           edgecolor='black', linewidth=.5)

    # Labels
    for i in range(len(cones)):
        ax.text(x[i] - w/2, 0.5, 'FP', ha='center', va='center',
                fontsize=9, fontweight='bold', color='white')
        ax.text(x[i] + w/2, 0.5, 'WL', ha='center', va='center',
                fontsize=9, fontweight='bold', color='white')
        if fp_match[i] and not wl_match[i]:
            ax.text(x[i], 1.08, 'FALSE\nPOSITIVE', ha='center',
                    fontsize=7, color=C['fp'], fontweight='bold')

    ax.set_xticks(x)
    ax.set_xticklabels(cones, fontsize=9)
    ax.set_yticks([])
    ax.set_ylim(0, 1.4)
    ax.set_title('Fig 6: Case Study — adder_4bit vs adder_4bit_mut2\n'
                 'Green = Match, Red = Mismatch',
                 fontweight='bold', fontsize=12)

    import matplotlib.patches as mp
    ax.legend(handles=[
        mp.Patch(color=C['matched'],   label='Match'),
        mp.Patch(color=C['unmatched'], label='Mismatch'),
    ], fontsize=9)
    _save(fig, 'thesis_fig6_case_study.png')


# ================================================================
#  GENERATE ALL
# ================================================================
def generate_all_thesis_plots():
    print("\n" + "=" * 70)
    print("  GENERATING THESIS PLOTS")
    print("=" * 70 + "\n")

    plot_scalability()
    plot_comparison()
    plot_match_distribution()
    plot_benchmark_overview()
    plot_convergence()
    plot_case_study()

    print(f"\n  All plots saved to {PLOTS_DIR}")


if __name__ == "__main__":
    generate_all_thesis_plots()
